### ISSUE TITLE
How to download ImageCLEF 2016 medical image public dataset ？

### ISSUE THREAD

**Issue by luowy1001** [razorx89/imageclef-med-2016-follow-up-research#1]
Hi，I have some problem that I cannot find the ImageCLEF 2016 medical image public dataset(30 modalities;6776 training images, and 4166 test images) .
Can you help me?
Thx! @razorx89

**Comment by razorx89** [comment]
You need to contact the organizers of the task (https://www.imageclef.org/2016/medical) and ask for licensing the dataset. Unfortunately, we are not allowed to distribute the dataset.
